
Vagrant.configure("2") do |config|
   
     config.vm.define "ElasticServ" do |web|
 	web.vm.box = "sbeliakou/centos"
	web.vm.network "private_network", ip: "192.168.56.155"
	web.vm.hostname = "ElasticServ"
	web.vm.provision "shell", path: "elk.sh"
        web.vm.provider "virtualbox" do |vb|
          vb.name = "ElasticServ"
          vb.memory = "2048"
	  end
      end


   config.vm.define "Tomcat" do |web|
	web.vm.box = "sbeliakou/centos"
	web.vm.network "private_network", ip: "192.168.56.156"
        web.vm.hostname = "Tomcat"
	web.vm.provision "shell", path: "tomcat.sh"
	web.vm.provider "virtualbox" do |vb|
	  vb.name = "Tomcat"
	  vb.memory = "2048"
	end
    end



end


